source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Caishen_Example' do
  platform :ios, '12.0'

  pod 'Caishen', :path => '../'
#  pod 'CardIO'
end

target 'Caishen_Tests' do
  platform :ios, '12.0'

  pod 'Caishen', :path => '../'
end
